### ISSUE TITLE
Go build on Darwin 10.8.0

### ISSUE THREAD

**Issue by FarnazMostowfi** [shirou/gopsutil#183]
Hi Guys, 
I am trying to install Telegraf on Darwin 10.8 and I get this error: github.com/shirou/gopsutil/cpu.Cvar_mach_task_self: undefined: mach_task_self_ 
Any idea what is happening? is this a compatibility problem? 
Appreciate your help.
Farnaz

**Comment by shirou** [comment]
It seems your golang can not use cgo. What version of golang? And how have you install golang?

**Comment by shirou** [comment]
I close this issue. If you have any problem, please re-open. Thank you.

**Comment by flyingsky** [comment]
same error here when I debug go in gogland for go version 1.7.5 and 1.8.0. But I can run it without debug.

```
GOROOT=/usr/local/Cellar/go/1.7.5/libexec
GOPATH=/Users/lianmeng/Uber/go:/Users/lianmeng/Uber/go
/usr/local/Cellar/go/1.7.5/libexec/bin/go build -o "/private/var/folders/ct/6z9hqc6j32v8qh5gwscfh_sc0000gn/T/Build main.go and rungo" -gcflags "-N -l" "-ldflags=-linkmode internal" /Users/lianmeng/Uber/go/src/code.uber.internal/everything/bazaar/main.go
# command-line-arguments
code.uber.internal/everything/bazaar/vendor/github.com/shirou/gopsutil/cpu._Cvar_mach_task_self_: mach_task_self_: not defined
code.uber.internal/everything/bazaar/vendor/github.com/shirou/gopsutil/cpu._Cvar_mach_task_self_: undefined: mach_task_self_
```

**Comment by wangxufire** [comment]
same issue on macos 10.12.5 use golang 1.8.1
