### ISSUE TITLE
compile error for linux and arm under mac osx

### ISSUE THREAD

**Issue by xurwxj** [shirou/gopsutil#591]
when execute:
```
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o dist/xxx.linux
or
CGO_ENABLED=0 GOOS=linux GOARCH=arm go build -o dist/xxx.arm
```
get error:
```
vendor/github.com/shirou/gopsutil/disk/disk_linux.go:394:11: undefined: unix.Major
vendor/github.com/shirou/gopsutil/disk/disk_linux.go:395:11: undefined: unix.Minor
```
source code:
```
func osInfo() {
	c, _ := cpu.Info()
	n, _ := host.Info()
	i, _ := net.Interfaces()
	v, _ := mem.VirtualMemory()
	fmt.Println("cpu: ", c)
	fmt.Println("host: ", n)
	fmt.Println("net: ", i)
	fmt.Println("mem: ", v)
	path := "/"
	if n.OS == "windows" {
		path = "\\"
	}
	diskStat, _ := disk.Usage(path)
	fmt.Println("disk: ", diskStat)

}
```
if remove all code after 4th fmt.Println, no error occured during compile

Go: v1.11 darwin/amd64

**Comment by Lomanic** [comment]
Looks like you are missing `golang.org/x/sys/unix` can you, try `GOOS=linux go get golang.org/x/sys/unix` before compiling?

**Comment by shirou** [comment]
I confirmed
https://gist.github.com/shirou/a5ce02b7ba980a8456b9f252a325f240
is working on my go1.9 on linux env.

**Comment by shirou** [comment]
And @Lomanic is correct. please go get `golang.org/x/sys/unix` or use `dep ensure`

**Comment by Lomanic** [comment]
Hopefully @xurwxj fixed his issue.

**Comment by xurwxj** [comment]
tks @Lomanic  @shirou .
fixed after get golang.org/x/sys/unix from github.com/golang/sys/unix
