### PR TITLE
[process][windows] Fix #1216 fix compilation on arm/arm64

### LINKED ISSUE #1216: v3.21.12: compilation error on Windows arm64
**Describe the bug**
The `process` module does not compile on Windows arm64 in v3.21.12, it works in v.3.21.11

**To Reproduce**
```go
package main

import (
	"fmt"

	"github.com/shirou/gopsutil/v3/process"
)

func main() {
	procs, err := process.Processes()
	if err != nil {
		panic(err)
	}
	fmt.Printf("processes: %+v\n", procs)
}
```

**Expected behavior**

this code should compile

**Environment (please complete the following information):**
 - [X] Windows: the version used in GitHub actions, take a look [here](https://github.com/drakkan/sftpgo/runs/4701720408?check_suite_focus=true)
 - [X] Linux: 
```
cat /etc/os-release 
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux-logo

uname -a
Linux p1 5.15.12-arch1-1 #1 SMP PREEMPT Wed, 29 Dec 2021 12:04:56 +0000 x86_64 GNU/Linux
```
**Additional context**

the GitHub actions cross compile from windows amd64 to windows arm64, take a look [here](https://github.com/drakkan/sftpgo/blob/main/.github/workflows/development.yml#L61)

on my Linux laptop I can reproduce trying to compile the code above

```
env | grep GO
GOARCH=arm64
CGO_ENABLED=0
GOOS=windows

go build 
# github.com/shirou/gopsutil/v3/process
/home/nicola/go/pkg/mod/github.com/shirou/gopsutil/v3@v3.21.12/process/process_windows.go:412:11: undefined: readProcessMemory
/home/nicola/go/pkg/mod/github.com/shirou/gopsutil/v3@v3.21.12/process/process_windows.go:425:11: undefined: readProcessMemory
/home/nicola/go/pkg/mod/github.com/shirou/gopsutil/v3@v3.21.12/process/process_windows.go:896:32: undefined: PROCESS_MEMORY_COUNTERS
/home/nicola/go/pkg/mod/github.com/shirou/gopsutil/v3@v3.21.12/process/process_windows.go:897:10: undefined: PROCESS_MEMORY_COUNTERS
/home/nicola/go/pkg/mod/github.com/shirou/gopsutil/v3@v3.21.12/process/process_windows.go:910:50: undefined: PROCESS_MEMORY_COUNTERS
/home/nicola/go/pkg/mod/github.com/shirou/gopsutil/v3@v3.21.12/process/process_windows.go:950:21: undefined: queryPebAddress
/home/nicola/go/pkg/mod/github.com/shirou/gopsutil/v3@v3.21.12/process/process_windows.go:955:9: undefined: readProcessMemory
/home/nicola/go/pkg/mod/github.com/shirou/gopsutil/v3@v3.21.12/process/process_windows.go:961:8: undefined: readProcessMemory
/home/nicola/go/pkg/mod/github.com/shirou/gopsutil/v3@v3.21.12/process/process_windows.go:969:21: undefined: queryPebAddress
/home/nicola/go/pkg/mod/github.com/shirou/gopsutil/v3@v3.21.12/process/process_windows.go:974:9: undefined: readProcessMemory
/home/nicola/go/pkg/mod/github.com/shirou/gopsutil/v3@v3.21.12/process/process_windows.go:974:9: too many errors
```

### PR DESCRIPTION
**Pull request by Lomanic**
go build ./... with GOARCH=arm64 is otherwise failing with the following:

process\process_windows.go:412:11: undefined: readProcessMemory
process\process_windows.go:425:11: undefined: readProcessMemory
process\process_windows.go:896:32: undefined: PROCESS_MEMORY_COUNTERS
process\process_windows.go:897:10: undefined: PROCESS_MEMORY_COUNTERS
process\process_windows.go:910:50: undefined: PROCESS_MEMORY_COUNTERS
process\process_windows.go:950:21: undefined: queryPebAddress
process\process_windows.go:955:9: undefined: readProcessMemory
process\process_windows.go:961:8: undefined: readProcessMemory
process\process_windows.go:969:21: undefined: queryPebAddress
process\process_windows.go:974:9: undefined: readProcessMemory
process\process_windows.go:974:9: too many errors

### CODE REVIEW

**Comment by shirou** [comment]
Thank you! This PR works like a charm! (We should add windows/arm(64) targets to `build_test` in Makefile. I will open it on other PR)
